import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { setTimeout as wait } from 'node:timers/promises';
import assert from 'node:assert/strict';
import { legalMoves } from '../lib/game.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/Grey Icesea/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=mkdtempSync(join(tmpdir(),'2048-ui-check-')),port=21481,url=`http://127.0.0.1:${port}`;
const adminPassword=randomBytes(20).toString('hex');
const output=new URL('../test-results/',import.meta.url);mkdirSync(output,{recursive:true});
const server=spawn(process.execPath,['server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:String(port),DB_PATH:join(dir,'ui.sqlite'),ADMIN_PASSWORD:adminPassword},stdio:'pipe'});
server.stderr.on('data',data=>process.stderr.write(data));
let browser;const errors=[];
try{
  for(let i=0;i<100;i++){try{if((await (await fetch(url+'/api/state')).json()).engine.ready)break;}catch{}await wait(100);}
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.goto(url);await page.waitForFunction(()=>document.querySelectorAll('#board .cell[data-value]').length===16);
  assert.equal(await page.locator('.topbar nav .nav:visible').count(),3);
  assert.equal(await page.locator('#takeover').isDisabled(),true);
  const game=(await (await context.request.get(url+'/api/state')).json()).game;
  await page.evaluate(()=>{window.sawMotion=false;new MutationObserver(()=>{if(document.querySelector('#board .moving-layer'))window.sawMotion=true;}).observe(document.querySelector('#board'),{childList:true});});
  await page.locator('#board').focus();
  await page.keyboard.press({1:'ArrowLeft',2:'ArrowRight',3:'ArrowUp',4:'ArrowDown'}[legalMoves(game.board)[0]]);
  await page.waitForFunction(()=>document.querySelector('#steps').textContent==='1');
  assert.equal(await page.evaluate(()=>window.sawMotion),true);
  await page.screenshot({path:fileURLToPath(new URL('desktop.png',output)),fullPage:true});
  await page.locator('[data-page="lab"]').click();
  assert.equal(await page.locator('#ai-controls').isHidden(),true);
  await page.screenshot({path:fileURLToPath(new URL('lab-public.png',output)),fullPage:true});
  await page.locator('#account').click();await page.locator('#username').fill('admin');await page.locator('#password').fill(adminPassword);await page.locator('#auth-submit').click();
  await page.waitForFunction(()=>!document.querySelector('#auth-dialog').open);
  assert.equal(await page.locator('#admin-nav').isVisible(),true);
  assert.equal(await page.locator('#ai-controls').isVisible(),true);
  await page.locator('#batch-count').fill('37');await page.locator('#batch-strength').fill('1.35');
  await page.locator('#batch-start').click();await page.waitForFunction(()=>document.querySelector('#batch-status').textContent==='运行中');
  assert.equal((await (await context.request.get(url+'/api/platform')).json()).batch.target,37);
  assert.equal((await (await context.request.get(url+'/api/platform')).json()).batch.strength,1.35);
  await page.locator('#batch-pause').click();await page.waitForFunction(()=>document.querySelector('#batch-status').textContent==='已暂停');
  await page.locator('.detail-card summary').click();await page.waitForSelector('#platform-runs table');
  await page.locator('#admin-nav').click();await page.waitForSelector('#machine-stats strong');
  await page.locator('#create-admin [name="name"]').fill('协管员');
  await page.locator('#create-admin [name="password"]').fill(randomBytes(20).toString('hex'));
  await page.locator('#create-admin button[type="submit"]').click();
  await page.waitForFunction(()=>document.querySelector('#admin-users')?.textContent.includes('协管员'));
  await page.screenshot({path:fileURLToPath(new URL('admin.png',output)),fullPage:true});
  await page.locator('[data-page="history"]').click();await page.waitForSelector('#history-summary strong');
  await page.setViewportSize({width:375,height:812});
  await page.locator('[data-page="play"]').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:fileURLToPath(new URL('mobile.png',output)),fullPage:true});
  assert.deepEqual(errors,[]);
  const report={passed:true,checks:['three page navigation','AI takeover disabled','animated movement','public AI display','admin controls','test detail expansion','machine panel','create limited admin','mobile width','zero browser errors']};
  writeFileSync(new URL('ui-report.json',output),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser?.close();server.kill();}
